name: Deploy to Cloudflare

on:
  workflow_dispatch:
     
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: actions/checkout@v4
      
      - name: 设置Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: 设置pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: false
          
      - name: 安装依赖
        run: pnpm install
        
      - name: 升级Wrangler到最新版本
        run: pnpm add -D wrangler@latest
        
      - name: 显示环境信息
        run: |
          echo "Node.js版本:"
          node --version
          echo "pnpm版本:"
          pnpm --version
          echo "Wrangler版本:"
          pnpm exec wrangler --version
          
      - name: 检查环境变量（安全处理）
        run: |
          if [ -n "${{ secrets.CF_API_TOKEN }}" ]; then
            echo "CF_API_TOKEN 已设置"
          else
            echo "CF_API_TOKEN 未设置"
          fi
          if [ -n "${{ secrets.CF_ACCOUNT_ID }}" ]; then
            echo "CF_ACCOUNT_ID 已设置"
          else
            echo "CF_ACCOUNT_ID 未设置"
          fi
          
      - name: 直接使用pnpm和Wrangler部署
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
        run: pnpm exec wrangler deploy
